# Generated by Django 6.0.5 on 2026-05-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('doctor', 'Doctor'), ('paciente', 'Paciente')], max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, default='', max_length=100)),
                ('matricula', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
