# Generated by Django 6.0.3 on 2026-05-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditoriadb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodb',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
