# Generated by Django 4.2.30 on 2026-05-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
