# Generated by Django 4.2.30 on 2026-05-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.CharField(default='08:00', max_length=10)),
                ('hora_fin', models.CharField(default='12:00', max_length=10)),
                ('duracion_min', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('cobertura', models.FloatField()),
                ('activa', models.BooleanField(default=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('creada_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('obra_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('estado', models.CharField(default='PENDIENTE', max_length=50)),
                ('costo_total', models.FloatField(default=10000.0)),
                ('cubre_os', models.FloatField(default=0.0)),
                ('paga_paciente', models.FloatField(default=10000.0)),
                ('detalle_costo', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.paciente')),
            ],
        ),
    ]
