# Generated by Django 4.2.30 on 2026-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocialDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cobertura', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'obras_sociales',
                'ordering': ['nombre'],
            },
        ),
    ]
