# Generated by Django 4.2.30 on 2026-06-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_obrasocialdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflacionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7, unique=True)),
                ('porcentaje', models.FloatField()),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inflacion',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.AddField(
            model_name='turnodb',
            name='costo_anterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnodb',
            name='motivo_consulta',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='turnodb',
            name='notas_medico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='turnodb',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN ATENCION', 'En Atención'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('AUSENTE', 'Ausente')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificacionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('SISTEMA', 'Sistema')], max_length=10)),
                ('destinatario', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='turnos.turnodb')),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
