# Generated by Django 4.2.30 on 2026-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_inflaciondb_turnodb_costo_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciondb',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
