# Generated by Django 6.0.5 on 2026-05-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=100)),
                ('paciente_dni', models.CharField(max_length=20)),
                ('paciente_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('paciente_email', models.CharField(blank=True, default='', max_length=100)),
                ('paciente_obra_social', models.CharField(blank=True, default='', max_length=100)),
                ('medico_nombre', models.CharField(max_length=100)),
                ('medico_especialidad', models.CharField(max_length=100)),
                ('medico_matricula', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN ATENCION', 'En Atención'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('duracion', models.IntegerField(default=20)),
                ('costo_total', models.FloatField(default=10000.0)),
                ('cubre_os', models.FloatField(default=0.0)),
                ('paga_paciente', models.FloatField(default=10000.0)),
                ('detalle_costo', models.CharField(default='', max_length=200)),
                ('motivo_cancelacion', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'turnos',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
